### PR TITLE
Fixes bell press issue #63

### PR DESCRIPTION
**Pull request by PhilPearson**
I add one line of code and git reports 101 additions and 100 deletions?? weird.

anyway, after the timer expires i explicitly set this.isOn to false.
Fixes the issue here on my test bench.

### CODE REVIEW

**Comment by DarylMc** [comment]
@anthonywebb 
Hi Anthony
Nice to see you back here.
Homebridge CBus works so reliably it's insane.

**Comment by DarylMc** [comment]
Well you see the little problems.
Aside from that it's all been rock solid in operation.

**Comment by anthonywebb** [comment]
@DarylMc @PhilPearson nice to have guy like you pulling on the oars and helping things along!  I'm really wanting to get my pi3 set up to try that.  I keep telling myself next time everything breaks I will do it, but things just stay online :) Love this project. 0.6.3 is live now, thanks for the fix.

**Comment by DarylMc** [comment]
do it anthony
pi3 has just been running without fault for me.
I've set up some SD cards for people remotely and all working amazing
thanks to you

**Comment by DarylMc** [comment]
send me your project xml and i will send you an image for pi3.
It is almost too easy but I wouldn't have said that just a few months ago

**Comment by DarylMc** [comment]
@anthonywebb 
i just got a new internet connection here in Australia .
I'm out in the suburbs so it is particularly awesome.
Many times faster than I ever expected.
90Mb/s
30Mb/s upload

**Pull request merged**
