### PR TITLE
Determine accessory type from database (#33) and Capturing changes on a remote network (#45)

### PR DESCRIPTION
**Pull request by simonhac**
* when auto-generating the accessory list, look at the units controlled by the group to come up with a ‘best guess’ of the accessory type, where possible
* cgate-database updated to support multiple networks

### CODE REVIEW

**Comment by simonhac** [comment]
@anthonywebb please consider this PR to address #33 and #45.

i've tested it with my project (which only has one network, but i faked a second) and @greiginsydney's `19P` project (which i can only partially test because i don't have access to the physical network).

it's worth enabling a database export (by adding something like `"database_export": "output/my-database.json"` to the platform config) to get a new view of your configuration. also worth re-running the unified device discovery thingy as it now picks up all relays, dimmers, fans, shutters and (most?) sensors.

**Comment by simonhac** [comment]
oops, i just tried it with my old single network cgate and encountered an error:

```
  cbus:db Parsing database (233.87 kB) +0ms
  cbus:client rx unparsable line: '[100] 344 End XML snippet', error: TypeError: Cannot read property 'address' of undefined
  cbus:client     at _arrayize.forEach.srcApp (/Users/simon/dev/homebridge-cbus/lib/cgate-database.js:102:88)
  cbus:client     at Array.forEach (native)
  cbus:client     at _extractApplicationsAndGroups (/Users/simon/dev/homebridge-cbus/lib/cgate-database.js:101:33)
  cbus:client     at _.forEach.network (/Users/simon/dev/homebridge-cbus/lib/cgate-database.js:235:3)
  cbus:client     at /Users/simon/dev/homebridge-cbus/node_modules/lodash/lodash.js:4944:15
  cbus:client     at baseForOwn (/Users/simon/dev/homebridge-cbus/node_modules/lodash/lodash.js:3001:24)
  cbus:client     at /Users/simon/dev/homebridge-cbus/node_modules/lodash/lodash.js:4913:18
  cbus:client     at Function.forEach (/Users/simon/dev/homebridge-cbus/node_modules/lodash/lodash.js:9359:14)
  cbus:client     at _processDatabase (/Users/simon/dev/homebridge-cbus/lib/cgate-database.js:234:4)
  cbus:client     at CGateDatabase.fetch.client.getDB.xml2js.parseString (/Users/simon/dev/homebridge-cbus/lib/cgate-database.js:74:19) +3m
```

pretty sure i know what the issue is. will fix tomorrow.

**Comment by simonhac** [comment]
@anthonywebb should now be ready to go -- have added tests for both single- and multi-network projects.

**Comment by anthonywebb** [comment]
@simonhac merged and published 0.6.1, awesome stuff!

**Pull request merged**
