### PR TITLE
added some files

### PR DESCRIPTION
**Pull request by DarylMc**
testing to see if i can upload some files keep them in a safe place and use wget to get them onto pi3
it's ok to say no
i dont really know exactly what I am doing

### CODE REVIEW

**Comment by simonhac** [comment]
@DarylMc be sure not to upload anything that's not open source -- ie. java, cgate.

**Comment by DarylMc** [comment]
oh dear i really don't know what i am doing
they are the files like config.json, homebridge and homebridge.service
i was having trouble using onedrive to download them with wget so i thought i might try here.
hope i havent mucked anything up

**Comment by DarylMc** [comment]
if it is ok to put somewhere maybe it needs to be in a folder called called pi3 config files
maybe just in my fork?
im open to advice

**Comment by DarylMc** [comment]
the plan was to upload a bunch of generic zipped config files and try to automate the whole install with curl leaving just one or 2 files to manually edit.
i know you have your own things going so if you say so im happy to just wait for that.
The image I uploaded seems to be running really well.
I haven't tried to kill it yet by dropping the LAN or CNI or power but it is looking good.
Will do some of that tonight.

**Comment by anthonywebb** [comment]
@DarylMc we should probably not put these zip files in the root of the project, just to avoid confusion on what they are for and how they work.  Perhaps a PI3 folder with its own readme file is in order?

**Comment by simonhac** [comment]
loving your work @DarylMc. i'll get a chance to try it in the next few months. (just bought my first pi.)

the general philosophy of github/open source is going in the direction of small projects that do one thing.

as such, perhaps pi-homebridge-cbus-cgate might be better off as its own module? just a thought.

**Comment by anthonywebb** [comment]
Thinking about this some more and wondering if @simonhac is correct.  Running CGate easy/solid on a PI3 is a great project in and of itself.  Having the option for it also to be running homebridge for easy config and deployment would be very valuable.  It probably is a big enough initiative that it deserves its own project, with its own issue tracking, etc.  Then we could link from our readme to @DarylMc project.

**Comment by DarylMc** [comment]
@simonhac @anthonywebb 
I'm going to try to move the zip files but I am having trouble figuring out how to do it.
Feel free to move any of it around or remove it.
In the fork I added my file link to the wiki.
The zip files can be found there anyway.

**Comment by DarylMc** [comment]
At this stage I am struggling to comprehend the whole github environment and will keep working on my onedrive links until i can figure out a better way to do it.

**Pull request closed without merging**
